# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thomas Visser
tagline:             
description:         
url:                 http://www.thomasvisser.me
baseurl:             
paginate:            5

# About/contact
author:
  name:              Thomas Visser
  url:               https://twitter.com/thomvis88
  email:             

# Custom vars
version:             1.0.0
