# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Thomas Visser
tagline:             Colorless green ideas sleep Swiftly
description:         
url:                 http://www.thomasvisser.me
baseurl:             
paginate:            100

# About/contact
author:
  name:              Thomas Visser
  url:               https://twitter.com/thomvis
  email:             

# Custom vars
version:             1.0.0

gems: ['jekyll-paginate']

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge